// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "ZD,GKAGd~,S,`s,|Jeas":
            case "amogusMouse2":return img`
.............................
.............................
.............................
....f........................
....f........................
....f........................
.....f........fff............
.....f.......f991fff.........
.....ff.....fc991df7f........
......f....f7c9991c77f.fffff.
......ff...77cc999b77fcbdddf.
......ff..f77fccccf77f11111d.
......f6ff.f77fcccc77f11111bf
.......ff.ff777777777f11dbd1f
.......ff.ff777777777fcbbbbc.
.......f6fff7777777776ffffff.
........ff..f777777766fdddbf.
........f6f.f77777766ffddcf..
....f.f.f6fff777666ffffffff..
...ff....f6fc766fff677.......
..f7cfffffff777cf6667f.......
..f677777777667ff66cf........
...f666666666fff6fff.........
...f6f66666666cc6f...........
...f66ffffc666c.f............
...f666f..f666f..............
...f666f..f666f..............
....ffff..f666f..............
..........ffcff..............
.............................
.............................
.............................
`;
            case "DF+lvdY15j$czyLP~5b6":
            case "POLUS":return img`
8888888888888888888888888888888888888888888888888888888888888888
8ffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffff8
8ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8
8ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8
8fcfffffffffffffffffffffffccbccccccccbbccffffffffffffffffffffff8
8fcfffffffffffffffffffffbdbccfcccccccccbdbfffffffffffffffffffff8
8ffffffffffffffffffffcbbccdddddd1ddbbbccfcbbcffffffffffffffffff8
8fffffffffffffffffffcbbcbdddddddddbbbbcccccbbcfffffffffffffffff8
8fffffffffffffffffcbbcbd1ddddddddbbbbccccccccbbcfffffffffffffff8
8ffffffffffffffffcbccb11dddddddbbbbbcccccccccccbcffffffffffffff8
8fffffffffffffffcbccb111dddddbbbbbbcccccccccccccbcfffffffffffff8
8ffffffffffffffcbccd11dddddbbbbbbbbccccccccccccccbcffffffffffff8
8fffffffffffffcbccdd1dddddbbbbbbbbccccccccccccccccdffffffffffff8
8ffffffffffffcbcbdd1dddddbbbbccccccccccccccccccccccbcffffffffff8
8ffffffffffffbccdddddddddbbcccccccccccccccccccfcccccbffffffffff8
8fffffffffffcbcd1dddddddbbccccccccccccccccccccccccccccfffffffff8
8fffffcbbbbbdbd111dd11dddbbcccbbcccccccccbbcffcbdbccbdbbbbbccff8
8fffcbbcccccccb111bcccccccbbbdbdbcccccccbddcffcbbdddbccccccbbcf8
8fffcbcccccccccb1dcccccccccbdbccdccccccbbcbcffbbccddccccccccbcf8
8fffcbcccccccccb1bcccccccccbdcccdcccccfbbccbffdbccddccccccccbbf8
8fffcbcccbbbbccb1bcccbbbcccbdcccdeeccfbdbccbffdbccddcccbbbccbbf8
8fffcbccbbbbdccb1bccbbbdbccbdcccdbecccbbbccbffdbccddccbbcdccbbf8
8fffcbcccbcbdccb1bccbbcbbccbdcccdbecfbfbbccbffdbccddccbcfdccbbf8
8fffbbccbbcbdccb1bccbbcbbccbdcccdeccfbfbbccbffdbccddccbcfbbcbcf8
8cccbbccbbcbdccb1bccbbcbbccbdcccdccccdfbbccbffdbccddccbcffddbff8
8cccbbccbdddbccb1bccbbcbbccbdcccdccccbfbbccbffdbccddccbbcccccfc8
8cccbbcccccccccb1bccbbcbbccbdcccdccccbfbbccbffdbccddcccbbbbbbcb8
8cccbbcccccccccb1bccbbcbbccbdcccdccfbbfbbccbffdbccddccccccccbbc8
8cccbbcccccccccd1bccbbcbbccbdcccdcccbcfbbccbffdbccddccccccccbbf8
8cccbbccbdbbdddddbccbbcbbccbdcccdcccbcfbbccbffdbccdcdbbbbbccbbf8
8cccbbccbbccbddddbccbbcbbccbdcccdcccbffbbccbffdbccdfcbddd1ccbbf8
8cccbbccbbcccbbbdbccbbcbbccbdcccdcccbcfbbccbffdbccdffbccbdccbbf8
8cccbbccbbccccbbdbccbbcbbccbdcccdccccbfbbccbffdbccdcbdbbbdccbbf8
8cccbbccbbcccccbdbccbbcbbccbdcccdeccfcbbbccbffdbccdbbbbdbdccbbf8
8cccbbccbbccccccbbccbbcbbccbdcccdeeccfbdbccbffdbccddccbdbdccbbf8
8cccbbcccbbcccccbbccbbcbbccbdcccdeeeccfbbccdbcdbccddccbdcdccbbf8
8fcfbbcccbbcccccbbccbdbdbccbdcccdbbebccbbccbb1dbccddccbdb1ccbbf8
8ccfbbccbcbcccccbbcccbbbcccbdcccbbbbbbddbccbbbbcccddcccbbbccbbf8
8ccfbbccbccbccccbbcccccccccbdcccccccccbdbcccccccccddccccccccbbf8
8ccccbccbccbccccbbcccccccccbdbccccccccbdbcccccccccddccccccccbbf8
8ccccbbbbcccbccccdbbbbbbbbbdddbbbbbbbbdddbbbbbbbbdcbdbbbbbbbbcf8
8ccccccccccccbccccbbbbccbdd455dddddddd555dddddddbccccbcccccccff8
8ccccccccccccdcccccccccce4555544444445445555555eecccbcfffffffff8
8ccccccccccffcbcccccccccce45555444444444555555eeccfbcffffffffff8
8ccccccccfffffbcccccccccccee44554444444444444eeccfbcfffffffffff8
8cccccffffffffcccccccccccccceee4444444eeeeeeecccccbffffffffccff8
8ccccffffffffffcbccccccccccccceeeeeeeecccccccccccbfffffffffccff8
8ccfffffffffffffcbcfccccccccccccccccccccccccccccbcfffffffffffff8
8fffffffffffffffffbbcfccccccccccccccccccccccfcdcfffffffffffffff8
8ffffbfffffffffffffbbccccccccccccccccccccccfcbcffffffffffffffff8
8ffffbfffffffffffffccbcccccccccccccccccccccbbffffffffffffffffff8
8ffffffffffffffffffbcfcbbcccffccccccccccbbbcfffffffffffffccffff8
8fffffffffffffffffffffffcccbbcccccccbbccccffffffffffccccccccfff8
8ffffffffffffffffffffffffffccccccccccccffffffffffcccccccccccccf8
8888888888888888888888888888888888888888888888888888888888888888
`;
            case "T4JX}(w*PRdKPGwRQBZg":
            case "FondoNegro":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffff
ffffffffffffffffffffffffff11111ffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffff
ffffffffffffffffffffffffff11111ffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffff
ffffffffffffffffffffffffff11111ffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffff11111ffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffff11111ffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffff11111ffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffff11111ffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff11111fffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff11111fffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff11111fffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "zq+K-^AARPPClM1K/{*j":
            case "POLUS2":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffcdbffffffffffcccccccffccccccffffffffffffffffffffccccff
fffffffc11111111ffffff111111111b1111111d111fffff11ffc11111111111
ffffffc111bfcb11bffffc11dddddd11dddddd11111cffff111f111111111111
ffffff111cddddc11ffffd1ccccccc11ccccccd1dc1dfffcd11f11b11cccccc1
fffff111b1ddddcc11fff1dcccccccd1ccccccb1cc11fffdcc1f1cc11ccccccc
ffff11f11ddddcbbc11ff1dcccccccb1ccccccb1ccd1fffdcc1c1cc11ccccccc
ffff11111dddbcbbcd1cf1dcc111ccb1c111bcb1ccd1fffdcc1c1cc11cc111cc
fff11c11ddddccbccc11f1dcc111ccb1c111bcb1ccd1fffdcc1c1cc11cc111cc
fff11111ddcccbbccc11f1dcc1d1ccb1c111bcb1ccd1fffdcc1c1cc11cc111cc
ffb1c11ddcbbbbc111c1b1dcc1c1ccb1c1d1bcb1ccd1fffdcc1c1cc11cc1d1cb
ff11d1ddbcbbbcc111c1d1dcc1b1ccb1c1d1bcb1ccd1fff1cc1c1cc11cc1d1b1
ff1111ddcbbbcc11c111d1dcc111ccb1c1d1bcb1ccd1fff1cc1c1cc11cc1d111
ff1b11dbcbbc4c1dfb11f1dcc111ccb1c1d1bcb1ccd1fff1cc1c1cc11cc11111
ff1f11dbccc5cb1ffffff1dcccccccb1c1d1bcb1ccd1fff1cc1c1cc11ccbbbbd
ff1f11dbcc55cd1ffffff1dcccccccb1c1d1bcb1ccd1fff1cc1c1cc11ccccccc
ff1f1ddbcc55c11ffffbc1dccccccc11c1d1bcb1ccd1fff1cc1c1cc11ccccccc
fc1f1ddcc455c11fffc111dccccccc11c1d1bcb1ccd1fff1cc1c1cc11ccccccc
fc1cddbc4554c11fff1111dcc1111111c1d1bcb1ccd1fff1cc1c1cc111111dcc
ff1bcdbc4554e11df11c11dcc1ddddf1c1d1bcb1ccd1fff1cc1c1cc1d11111cc
ff1ccdbc45422f1111dc11dcc1fffff1c1d1bcb1ccd1fff1cc1c1cc1bddb11cc
ff1ccdbc45222f1111ce11dcc1fffff1c1d1bcb1ccd1fff1cc1c1cc1111d11cc
ff1dcccbe544244cfcbd11dcc1fffff1c1d1bcb1ccd1fff1cc1c1cc11bb111cc
ff11ccbbe5444444e4e111dcc1fffff1c1d1bcb1ccd1fff1cc1c1cc11cc111cc
ffb1ccbbc555554454c1d1dcc1fffff1c1d1bcb1ccd1fff1cc1c1cc11cc111cc
fff1bbbbc55555555ec1f1dcc1fffff1c1d1bcb1ccd1fff1cc1c1cc11cc111cc
fff11ccbce555555cc11f1dcc1fffff1c111bcb1ccd11111cc111cc11cc111cc
ffff11ccccc555ecc11ff1dcc1fffff1cdddbcb1ccd11111cc111cc11ccdddcc
ffff11ccccccecccc11ff1dcc1fffff1ccccccb1ccccccb1ccccccc11ccccccc
ffffc11ccccccbbb11bff1dcc1fffff1ccccccb1cccccccdccccccc11ccccccc
ffffff11dccccccd1ffff11cd1fffff1ccccccd11ccccccdccccccc11ccccccd
ffffff111dcccf111ffffb1d11fffff1bbbbbb111dbbbbb11dbbbbd111dbbbd1
fffffffd11111111ffffff111bfffffd1111111c111111111111111111111111
ffffffff11111111ffffff111fffffff1111111f111111111111111db1111111
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "`wH0YPN!fsyLd^l*p_Cf":
            case "The Skeld":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
ffcddbbcbdbbfcbdddddbbbfcbbbdbbfffffcbbcfbbfcbcbdddbbcffcbbbffff
ffcddbbcbdbbfcbdddddbbbfcbbbdbbfffffcbbcfbbfcbcbdddbbcffcbbbffff
ffdccbbdbccbbdbbbbbbbddfbbdbbbdffffcdbbddddc1d1bbbbbddffbbbddcff
ffdcccccbbcbcbd11bd11bbcbcbb11dffffbbddbddd1cb1b1111bdcfbcdbbdff
ffbcccccbcbdfffbbddccbbcbcbbcffffffbcdccbdddbddbdffcbdcfbcdbcbff
ffbcccccbcbdfffbbddccbbcbcbbcffffffbcdccbdddbddbdffcbdcfbcdbcbff
ffbccccccccbcffbbddcfbbcbcbbcffffffbcdbfcdbb1cdbdffcbdcfbcbfbbcf
ffcbccccccccdffbbddcfbbddcbcdddffffcdccdddcdcfdbddd1bdcfbcbfdbbf
ffbbcbccccccbbfbbddcfbcbbcbcbbdfffffcdbbddcbbfdcbbbbbdcfbcbfbbbf
ffbbcbccccccbbfbbddcfbcbbcbcbbdfffffcdbbddcbbfdcbbbbbdcfbcbfbbbf
ff1cbccccccccdcbbddcfbbbdcbbddbfffffffcbbdbb1cdb1dddbdcfbcbfbbcf
ffdccbccccccbdfbbddcfbbcbcbbcffffffddcfdbdd1cd1bdffcbdcfbcddcbff
ffcbbbbbcccbbcfbbddcfbbcbcbbbbcffffdbbbdbdddbb1b1bbbbdbbdcddbdff
ffcbbbbbcccbbcfbbddcfbbcbcbbbbcffffdbbbdbdddbb1b1bbbbdbbdcddbdff
fffbcfcdbcbdfffbbddcfbbcbcbcbbdcfffbbcccdddb1bdcbbbbbccbbcccdcff
ffffffffbddffffffddffddfcdd111dfffffbdddcddfcddd111dd11dddddffff
fffffffffcfffffffffffffffffffcfffffffccfffffffffffffffffffffffff
fffffffffcfffffffffffffffffffcfffffffccfffffffffffffffffffffffff
1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image1":
            case "lobbyfondotest":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "ZSw}PAv[Oxwj;kU~Wkut":
            case "amongusFoto":return img`
fffffffffffffffc1bccbb11cffffffffffffffc1cffffffffffcdcfffffffbdff11ffffffc11cfffffffdbfffffdd1dccdfffffffffffffffffffffffdcfffffffffff1cfffffb1dcfbd1bfffffffff
fffffffffffffffc1bccbb11cffffffffffffffc1cffffffffffcdcfffffffbdff11ffffffc11cfffffffdbfffffdd1dccdfffffffffffffffffffffffdcfffffffffff1cfffffb1dcfbd1bfffffffff
ffffffffffffffbbfffffffcbbcffffffffffffc1dffffffffffb1cfffffffbffccdddffcfc11bfffffffdbffffcddcfffffffffffffffffffffffffffdcfffffffffff1cfffccdcfffffcbfffffffff
fffffffffffffbcfffffffffffbcfffffffffffc11ffffffffffd1cffffffcbffffc11cfffc1bdfffffffdcffffdccfffffcffffffffffffffffffffffbcfffffffffff1cfffddcfffffffffffffffff
fffffffffffffbcfffffffffffbcfffffffffffc11ffffffffffd1cffffffcbffffc11cfffc1bdfffffffdcffffdccfffffcffffffffffffffffffffffbcfffffffffff1cfffddcfffffffffffffffff
ffffffffffffcbffffffffffffcdbffffffffffb11cfffffffff1dcffffffccfffffbbbfffc1fbcffffffdcfffbdffffffffffffffffffffffffffffffbcffcffffffff1cffcbbffffffffffffffffff
ffffffffffffdcfffffffffffffbcffffffffffdd1cfffffffffdcbffffffccfffffccdfffc1fcbffffffdcfff1bffffffffffffffffffffffffffffffbcfffffffffff1cffdbbffffffffffffffffff
ffffffffffffdcfffffffffffffbcffffffffffdd1cfffffffffdcbffffffccfffffccdfffc1fcbffffffdcfff1bffffffffffffffffffffffffffffffbcfffffffffff1cffdbbffffffffffffffffff
fffffffffffcdffcbbddddbcfffbdcfffffffff1cbbffffffffcbcbffffffbcfffffffdfffc1fcdffffff1cffc1cffffffffffffffffffffffffffffffbcfffffffffff1cffdccffffffffffffffffff
fffffffffffbcfdccfffccccbffcdbbfcffffff1ccbffffffffbbcbffffffdcfffffffbcffc1ffdcfffff1cffc1fffffffffffffffffffffffffffffffbcfffffffffff1cffdffffffffffffffffffff
fffffffffffbcfdccfffccccbffcdbbfcffffff1ccbffffffffbbcbffffffdcfffffffbcffc1ffdcfffff1cffc1fffffffffffffffffffffffffffffffbcfffffffffff1cffdffffffffffffffffffff
fffffffffffdfbcfffffffffdfffbfbcffffffcdffdffffffffdbfbffffffdcfffffffbcffc1ffdcfffff1bffb1fffffffffffffffffffffffffffffffbcfffffffffff1ccc1ffffffffffffffffffff
ffffffffffcbfbffffffffffcbffdfcdffffffcdffdffffffffdcfbffffffdcfffffffbcccc1ffcbfffffdbffbbfffffffffffffffffffffffffffffffccfffffffffff1cccdffffffffffffffffffff
ffffffffffcbfbffffffffffcbffdfcdffffffcdffdffffffffdcfbffffffdcfffffffbcccc1ffcbfffffdbffbbfffffffffffffffffffffffffffffffccfffffffffff1cccdffffffffffffffffffff
ffffffffffccfbfffffffffffdffdffdbfffffbdffbcffcbfff1ffbcffbffdffffffffbcccc1ffcbfffffdbffbcffffffcffffffffffffffffffffffffccfffffffffff1bffdffffffffffffffffffff
ffffffffffbcfbfffffffffffdffbcfcdfffffdbffbbfffcffc1ffbcfffffdffffffffbbccc1fccbcccffdbffdcfffffffffffffffffffffffffccffffccfffffffffff1cffdccffffffffffffffffff
ffffffffffbcfbfffffffffffdffbcfcdfffffdbffbbfffcffc1ffbcfffffdffffffffbbccc1fccbcccffdbffdcfffffffffffffffffffffffffccffffccfffffffffff1cffdccffffffffffffffffff
ffffffffffbcfbcfffffffffcdffbbffdfffffdcffc1ffcfffcdffbcfffffdffffffffcbfcc1ccfdcffcfbbffdffffffffffffffffffffffffffffffffcbfffffffffff1cfcbddfffffffffffcffffff
ffffffffffbffccbccccbbbbbcffcdffbcfffcdffff1ffffffbcffccffffcdffffffffcbccc1cccdcccffbbccdffffffffffffffffffffffffffffffffcbfffffffffff1cffcddbcfffffffffcffffff
ffffffffffbffffffffffffffffff1ffccfffcdffffdccffffbcffcbffffcdffffffffcbccc1cccbbccccbbcc1ffffffffffffffffffffffffffffffffcbfffffffffffdcfffccddbfffffffffffffff
ffffffffffbffffffffffffffffff1ffccfffcdffffdccffffbcffcbffffcdffffffffcbccc1cccbbccccbbcc1ffffffffffffffffffffffffffffffffcbfffffffffffdcfffccddbfffffffffffffff
ffffffffffbffffffffffffffffff1ffcbfffcbffffbbbffffdfffcbffffcdffffffffcdfcc1cccbdccccbbcc1fcffffffffffffffffffffffffffffffcdfffffffffffdcffffffb11cfffffffffffff
ffffffffffbffffffffffffffffff1cfcbfffccffffcbbffffdfffcdffffcdffffffffcbccc1fccb1bcccbbcc1cfccffffffffffffffffffffffffffffcbfffffffffffdffffffffcb1bffffffffcfff
ffffffffffbffffffffffffffffff1cfcbfffccffffcbbffffdfffcdffffcdffffffffcbccc1fccb1bcccbbcc1cfccffffffffffffffffffffffffffffcbfffffffffffdffffffffcb1bffffffffcfff
fffffffffcdffffffffffffffffffdcfcbfffbcfffffbbfffcdfffcdffffcdffffffffcbccc1ccccdbbccbbcc1fccccfffffffffffffffffffffffffffcbfffffffffffdfffffffffff1bfffffffffff
fffffffffcbffffffffffffffffffbbffbfffbcfffffddfffcbcfffdffffcdffffcfffcbcfc1ccccddcbcbbcc1ccffcffffffffffffffffffffffffffffbffffffffffcdffffffffffffdbffffffffff
fffffffffcbffffffffffffffffffbbffbfffbcfffffddfffcbcfffdffffcdffffcfffcbcfc1ccccddcbcbbcc1ccffcffffffffffffffffffffffffffffbffffffffffcdffffffffffffdbffffffffff
fffffffffccffffffffffffffffffcbffbfffbcfffffbbcffbbffffdffffcdffffffffcbfcb1fcccddccbdbcc1cccccffffffffffffffffffffffffffffbcfffffffffcdffffffffffffc1bfffffffff
fffffffffccffffffffffffffffffcbffbfffbffffffbbcffdbffffbcffffdffffffffccccc1cccfcdcccbbcc1fcccccfffc11111ffffffffffffffffffbcfffffffffbbfffffffffffffc1cffffffff
fffffffffccffffffffffffffffffcbffbfffbffffffbbcffdbffffbcffffdffffffffccccc1cccfcdcccbbcc1fcccccfffc11111ffffffffffffffffffbcfffffffffbbfffffffffffffc1cffffffff
fffffffffccffffffffffffffffffcbfbbffcbffffffcccff1cffffbbcfffdcfffffffccccc1cfcccdbccbbcc1ccccccccfc1cccccfffffffffffffffffbcfffffffffdbfffcffffffffffcdffffffff
fffffffffccfffffffffffffffffff11dfffcbffffffcccff1cffffbdffffdcfffffffbcccb1ffcccbbccdbcb1cccccfbcfc1ffffffffffffffffffffffbcfffffffffdbffcbfffffffffffbdfffffff
fffffffffccfffffffffffffffffff11dfffcbffffffcccff1cffffbdffffdcfffffffbcccb1ffcccbbccdbcb1cccccfbcfc1ffffffffffffffffffffffbcfffffffffdbffcbfffffffffffbdfffffff
fffffffffccffffffcbbbbbcffffffdcffffcbffffffcccfc1fffffb1ffffdcfffffffbcccc1fffcccdceddeb1cccccffffb1ffffffffffffffffffffffccfffffffffdcffcbffffffffcffcdfffffff
fffffffcfccfffffc11d111bffffffdfffffccffffffcccfb1fffffc1ffffdcfffffffbbcfc1fffffc1cbddbb1bbeecffffb1ffffffffffffffffffffffcbffffffffc1cffcbffffffffffff1fffffff
fffffffcfccfffffc11d111bffffffdfffffccffffffcccfb1fffffc1ffffdcfffffffbbcfc1fffffc1cbddbb1bbeecffffb1ffffffffffffffffffffffcbffffffffc1cffcbffffffffffff1fffffff
fffffffffccfffffdbffff1bffffffdfffffbcffffffccbfbdfffcfc1ffffdcfffffffcfffc1fffffcdccddbbdbbccfffffbdffffffccffffffcfffffffcdffffffffc1fffcbffffffffffff1cffffff
fffffffffccffffc1fffffbdffffffdcffffdcffffffccdfbdffffff1cfffbcfffffffbfffc1cfffffbbfdbcd1dbfffffffbdffffffccffffffcfffffccc1ffffffffcdfffcdffffffffffff1cffffff
fffffffffccffffb1ffffff1cfffffdcffffdcffffffccdfbcffffff1cfffcbfffffffdfffc1ffffffbdfdbfdd1bfffffffbbffffffffffffffffffffffcdcfffffffbbfffc1fffffffffffcdfffffff
fffffffffccffffb1ffffff1cfffffdcffffdcffffffccdfbcffffff1cfffcbfffffffdfffc1ffffffbdfdbfdd1bfffffffbbffffffffffffffffffffffcdcfffffffbbfffc1fffffffffffcdfffffff
fffffffffccffffc1ffffff1cffccfdcffffdfffffffffdcdcfcffff1bfffcbfffffccbfffc1ffcfffc1cdbfcd1cfffffffdcfffffffffffffffffffffffbbfffcfffbcfffc1fffffffffffbdfffffff
fffffffffccfffcc1ffffff1cfffffdcfffcdfffffffffb11cffffffdbfffcbfffffddbfffc1fffffff1d1ccfc1cfffffff1cfffffcfffffffffffffffffb1fffcccfdfffffdccffffffffcdcfffffff
fffffffffccfffcc1ffffff1cfffffdcfffcdfffffffffb11cffffffdbfffcbfffffddbfffc1fffffff1d1ccfc1cfffffff1cfffffcfffffffffffffffffb1fffcccfdfffffdccffffffffcdcfffffff
fffffffffccffffc1ffffffdcfffffdcfffbbfffffffffb11fffffffbbffffdffffc11cfffc1fffffffb11cfff1bffffffbdfffffffffffffffffffffffffdcfffffbbfffffcbbfffffffcdbffffffff
fffffffffccffffc1ffffffdcfffffdcfffbbfffffffffb1dfffffffcbffffbcfffb11cfffc1fffffffc11cfffbdffffffdbffffffffffffffffffcffffffbdffffc1cffffffddfffffffb1cffffffff
fffffffffccffffc1ffffffdcfffffdcfffbbfffffffffb1dfffffffcbffffbcfffb11cfffc1fffffffc11cfffbdffffffdbffffffffffffffffffcffffffbdffffc1cffffffddfffffffb1cffffffff
fffffffffccfffcb1ffffffdcfffffdcfffbcfffffffffc1bffffffffdffffc1bcb1ccffffc1ffffffffd1fffffbddbccbdcfffffffcffffffffffcfffffffddcccdbfffffffccdbcfccddcfffffffff
fffffffffcddddd11ffffffbdddddd1cfffdcffffffffff1cffffffffdfffffc111bffffffc1ffffffffb1ffffffbb1111cfffffffffffffffffffffffffffcd1d1bfffcffffffcd1dd1bfffffffffff
fffffffffcddddd11ffffffbdddddd1cfffdcffffffffff1cffffffffdfffffc111bffffffc1ffffffffb1ffffffbb1111cfffffffffffffffffffffffffffcd1d1bfffcffffffcd1dd1bfffffffffff
ffffffffffbbbbbccffffffcbbbccccffffbfffffffffffbcffffffffbffffffcbcfffffffcbffffffffcbffffffffcbbcffffffffffffffffffffffffffffffcbbffffffffffffffcccffffffffffff
ffffffffffffffffbffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffbffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffcffbffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffff
ffffffffffffffffffffffffffffffffffccffffffffffffffffcffcffffffffffffffffffffffffffeeeeefffffffffffffffffffffffffffffccffcffffffffffffffffffffffcffffffffffffffff
ffffffffffffffffffffffffffffffffffccffffffffffffffffcffcffffffffffffffffffffffffffeeeeefffffffffffffffffffffffffffffccffcffffffffffffffffffffffcffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffeeeeefffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffccbb6bbbcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffccbb6bbbcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffec66666666666bbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffee6ccccccccccc66b99bfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffcfffffffffffffffffffffffccaaaaccfffffffffffffeeefeec6ccccccccccccc666bcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffcfffffffffffffffffffffffccaaaaccfffffffffffffeeefeec6ccccccccccccc666bcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaacffffffffffee2eee2c9cc66666cccccccccc6cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffcffcccaaaaaaaaaacfffcfffe22eee2eb9666666666c6666666c6ccfffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffcffcccaaaaaaaaaacfffcfffe22eee2eb9666666666c6666666c6ccfffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffcccccaaaaaaaaacccccee2eeee22eb1966666666c66666666bfccccfffffffffccffffffffffffffcfffffffffffffffffcfffffffffffffff
fffffffffffffffffffffffffffcffffffffffffffffccccccccccaaaaaaccccee2eeee222ecb999b66666666666cc6bfccccccccffffffffffffffffffffffffffffffcffffffffffffffffffffffff
fffffffffffffffffffffffffffcffffffffffffffffccccccccccaaaaaaccccee2eeee222ecb999b66666666666cc6bfccccccccffffffffffffffffffffffffffffffcffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffccfffffcccccccccaaaaaaccee22eeee222eeccbddd9bb6666666666bcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffcffffffffcccccccccccccaaaaaaae222eeee22222eeeecccbbbd9bbbbbbbbbccccccccccccccceeeeeffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffcffffffffcccccccccccccaaaaaaae222eeee22222eeeecccbbbd9bbbbbbbbbccccccccccccccceeeeeffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff6ccccccc6cccbcaaaaace22eee2222222222eeeeeccccccbbbbbbcceccccccccccce45444444efffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff6ccc6666666cbcaaaaae22eeee2222222222222eeeeeeeeeceeeeeeecccccceecee5554444444eefffffffffffffffffffffffffffffcbffffffff
ffffffffffffffffffffffffffffffffffffffffff6ccc6666666cbcaaaaae22eeee2222222222222eeeeeeeeeceeeeeeecccccceecee5554444444eefffffffffffffffffffffffffffffcbffffffff
ffffffffffffffffffffffffffffffffffffccfffc6c66b9999b66bcaaaace22eee222222222222222222eeeeeeeeeeeeeeccceeeeee555eceee4444eeffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffc6b999999999bbcaaaae22eeee22222222222222222222222222222eeeeeee44e45557cb6ccffe44effffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffc6b999999999bbcaaaae22eeee22222222222222222222222222222eeeeeee44e45557cb6ccffe44effffffffffffffffffffffffffffffffffffff
ffffffffffffffcffffffffffffffffffffffffffcb99999999999bcaaace22eee222222222222222222222222222222eeeeee444e5555cb66c6cccceeefffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffcfccfff99999dd1dddbcaaaaee2eeee2222222222222222222222222222222eee4444e55557cd666666cccceffffcffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffccccbbbbbbbccccaaaace22eee22222222222222222222222222222222eee444e45555eb9666666666ccffffccffffffffffbfffcffffffffffffffff
fffffffffffffffffffffffffffffffffffffffccccbbbbbbbccccaaaace22eee22222222222222222222222222222222eee444e45555eb9666666666ccffffccffffffffffbfffcffffffffffffffff
ffffffffffffffffffffffffffffffffffffffccccccccccaaaaaaaaaaee22eee22222222222222222222222222222222eee44e455555e19b66666cccccfffffffffffffffffffffffffffffffffffff
ffffffffffcffffffffffffffffffffffcccccccccccccaaaaaaaaaaaae22eeee22222222222222222222222222222222eee4e4555555c1d9666666666bccfffffee4effffffffffffffffffffffffff
ffffffffffcffffffffffffffffffffffcccccccccccccaaaaaaaaaaaae22eeee22222222222222222222222222222222eee4e4555555c1d9666666666bccfffffee4effffffffffffffffffffffffff
fffffffffffffffffffffffffffffffc6bdd1dbcccccccaaaaaaaaaaaceeeeeee222222222222222222222222222222222eee455555557ebbdb6666666ccccffe444444effffffffffffffffffffffff
ffffffffffffffffffffffdffcffffcbbbbbdddbccccccaaaaaaaaaaaeeeeeee2222222222222222222222222222222222eee55555555554ecbdbbbc6beeccce4444eeeeefffffffffffffffffffffff
ffffffffffffffffffffffdffcffffcbbbbbdddbccccccaaaaaaaaaaaeeeeeee2222222222222222222222222222222222eee55555555554ecbdbbbc6beeccce4444eeeeefffffffffffffffffffffff
fffffffffffffffffffffffffffffccccccccddd6bccccaaaaaaaaaaaeeeeeee2222222222222222222222222222222222ee45555555555554ecbbbbbceeeee4444eeeeeeeffffffffffffffffffffff
ffffffffffffffffffffffffffffcc6cccc6cbddbccccccaaaaaaaaaaeeeeeee2222222222222224444422222222222222eee555555555555554eeecee4eeee4444bcccccfffffffffffffffffffffff
ffffffffffffffffffffffffffffcc6cccc6cbddbccccccaaaaaaaaaaeeeeeee2222222222222224444422222222222222eee555555555555554eeecee4eeee4444bcccccfffffffffffffffffffffff
ffffffffffffffffffffffffffffc6ccccc66bdddcbccccaaaaaaaaaaceeeeee2222222224444444444444444242222222eee5555555555555555544444eee44444ccccccccfffffffffffffffbcffff
ffffffffffffffffffffffffffffccccc666bbddddcccccaaaaaaaaaaaeeeee22222224444444444444444444444444442eee5555555555555555544444eee4444ebbb666ccfffffffffffffffffffff
ffffffffffffffffffffffffffffccccc666bbddddcccccaaaaaaaaaaaeeeee22222224444444444444444444444444442eee5555555555555555544444eee4444ebbb666ccfffffffffffffffffffff
ffffffffffffffffffffffffffffc66666ccbbddddccccccaaaaaccaaabeeee24444444444444444444444444444444444eee5555555555555555544444ee44444eb999999cfffffffffffffffffffff
ffffffffffffffffffccccffffffccc66bbbbbddddbcccccaaaccccccaabeee444444444444444444444444444444444444ee4555555555555555544444ee444444eeebbbbcffffffffffffcffffffff
ffffffffffffffffffccccffffffccc66bbbbbddddbcccccaaaccccccaabeee444444444444444444444444444444444444ee4555555555555555544444ee444444eeebbbbcffffffffffffcffffffff
fffffffffffffffffc66bbcccffcbbbbbbbbddddddbcccccccccccccccaaeee444444444444444444444444444444444444ee4555555555555555544444ee44444444444eeefffffffffcfffffffffff
fffffffffccfffffc696ccccccfcbbdddddddddddddbcccccccccccaaabbeee444444444444444444444444444444444444ee455555555555555444444ee4444444444442eefffffffffffffffffffff
fffffffffccfffffc696ccccccfcbbdddddddddddddbcccccccccccaaabbeee444444444444444444444444444444444444ee455555555555555444444ee4444444444442eefffffffffffffffffffff
ffffffffffffffffcbcfccccccccbb1ddddddddddddcbbccccccccccaabbee4444444444444444444444444444444444444eee55555555555555444444ee4444444444442eeffffffffcffffffffffff
ffffffffffffffffffccccccccccbbdddddddddddddcbbcccccccccaabbbee4444444444444444444444444444444444444eee55555555555554444444e44444444444442eefffffffc7ccfffffcffff
ffffffffffffffffccccccccccccbbdddddddddddddccccccccccaaaabbeee444444444444444bb44444444444444444444eee4555555555555444444eee4444444444442efffffcfc76c6cfffffffff
ffffffffffffffffccccccccccccbbdddddddddddddccccccccccaaaabbeee444444444444444bb44444444444444444444eee4555555555555444444eee4444444444442efffffcfc76c6cfffffffff
ffffffffffffffffcccccccccccc6bddddddddddbcccccccccccaaaabbbeee444444444444444bbbbbbbbbb44bb444444444ee45555555555554444444ee444444444444eeffffccc77c699cffffffff
fffffffff8888fffcccccccccffc6bdddddddbcccccccccccccaaabbbbbeee444444444444444bbbddddddbbbbb444444444ee44555555555544444444ee444444444444eeefffcf7777666cffffffff
fffffffff8888fffcccccccccffc6bdddddddbcccccccccccccaaabbbbbeee444444444444444bbbddddddbbbbb444444444ee44555555555544444444ee444444444444eeefffcf7777666cffffffff
fffffffff888888fcccccccccfcbbddddddddccacccccccccaaaabbbbbbeee44444444444444bbbdd1ddddddbbb444444444be44555555555544444444ee444444444444eeefcccf7777ccccffffffff
ffffffffcc88888fcccccccccfcbdddddddddcaaaacccccaaaaabbbbbbbebe44444444444444bbd11111111dbbbb44444444be44455555555544444444ee444444444444eeefccf677777cffffffffff
ffffffffcc88888fcccccccccfcbdddddddddcaaaacccccaaaaabbbbbbbebe44444444444444bbd11111111dbbbb44444444be44455555555544444444ee444444444444eeefccf677777cffffffffff
fffffffccc888888fccccccccfcbddddbbbdbcaaaaccccaaaaaabbbbbbeebe4444444444444bbb1111111111dbbb44444444be44455555555544444444e444444eeeee444eeeccf777777ccfffffffff
fffffffff8888888fcccccccff6bdddbccccbbcaaaaaaaaaaaabbbbbbbebb44444444444bbbbbd11111111111bbb44444444be444444444455544444444444444eecce444eeeeec77777ccffffffffff
fffffffff8888888fcccccccff6bdddbccccbbcaaaaaaaaaaaabbbbbbbebb44444444444bbbbbd11111111111bbb44444444be444444444455544444444444444eecce444eeeeec77777ccffffffffff
cfccfcfff88888888fcccccffcbbdddcceeeebcaaaaaaaaaaabbbbbbbbebb444444444bb33bbbd11111111111dbbbb444444bbbbbbbbbbbee555444444444444eeeccce444eeeef7777fcfffffeeefff
cc7bcfcff88888888fccccffcccbdddcceeeecbcaaaaaaaaaabbbecbbbebb444444444b333bbb111111111111dbbbbb44444bbedddbbbbbbe4554444444e444eeeecccce444eeeef7777ccfffeeeefff
cc7bcfcff88888888fccccffcccbdddcceeeecbcaaaaaaaaaabbbecbbbebb444444444b333bbb111111111111dbbbbb44444bbedddbbbbbbe4554444444e444eeeecccce444eeeef7777ccfffeeeefff
fe77ffcff888888fffccccffcccbdddbceeeeecccaaaaaaaabcebbbbbbebb4444444bb3333bbd111111111111ddbbbb44444bbbddddbbbbbbe555544444eeeeeeeeccccee44eeeeeec776cfffeefefff
fffefffff8888888ffccccffcccbbddcceeeeeecccbaaaabcebbbbbbebebb444444b333333bb1111111111111ddbbbb34444bbbddddbbbbbbe455554444eedeeeeecccccee444444ffc777ccfefeefff
fffefffff8888888ffccccffcccbbddcceeeeeecccbaaaabcebbbbbbebebb444444b333333bb1111111111111ddbbbb34444bbbddddbbbbbbe455554444eedeeeeecccccee444444ffc777ccfefeefff
ffefffcff88888888fcccccfccccdbcceeeeeeeebbccccccebbbbbbddbbb444444bb33333bbb111111111111dddbbbbbb444bbbdddddbbbbbb4555544444ebeeeeecccccce4444ef7cfff776cfffffff
ffffffcf888f888888fccccfccccccceeeeeeeeebbbdbbebbbbbbbbddbeb444444b333333bbb111111111111ddddbbbbb444bbbddddbbbbbbbe555554444eeeeeeeecccccceeee77fffffc7fffffffff
`;
            case "v%REC~)2$Y5~wo/YD:Cf":
            case "BotonInicio":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
.........fffffffffffffffffffffffffffffffffffffffffffffff........
.......ffffffccccccccccccccccccccccccccccccccccccccfffffff......
.....ffffddddddddddddddddddddddddddddddddddddddddddddddcfff.....
....fffddddddddddddddddddddddddddddddddddddddddddddddddddfff....
...fffddddddddddddddddddddddddddddddddddddddddddddddddddddeff...
..fffddddddddddddddddddddddddddddddddddddddddddddddddddddddeff..
..ffddddddddddddddbbbbbddbbbbbbbdddddbddddbbbbbddddbbbbbbbddfff.
.ffbddcedddddddddffffffddfffffffdddffffeddcfffffbddfffffffbddff.
.ffdddcffdddddddffcbbbbddbbffbbbddfffeffddcfbbeffddbbefebbdddcf.
ffedddcfffbdddddffdddddddddffdddddffdddfedcfdddffddddbfeddddddff
ffddddcfcffcddddfffffddddddffdddddffdddffdcfdddffddddbfeddddddff
ffddddcf11fffddddfffffeddddffdddddffdddffdcfffffeddddbfeddddddff
ffddddcf111fffbddddddffddddffdddddfffffffdcfffffbddddbfeddddddff
ffddddcf111bfffddddddffddddffdddddfffffffdcfdddffddddbfeddddddff
ffddddcf11fffbddbffffffddddffdddddffdddffdcfdddffddddbfeddddddff
ff4dddcf1fffddddbfffffdddddffdddddffdddffdcfdddffddddbfeddddddff
ffedddcfffcdddddddddddddddddddddddddddddddddddddddddddddddddd4ff
.ff4ddcffbdddddddddddddddddddddddddddddddddddddddddddddddddd4eff
.ff44dcfddddddddd1dd11111111111111111111111111111111dd1dddd44ff.
..ff44edddddddddd1dd11111111111111111111111111111111dd1ddd44eff.
..ffe444dddddddddddddddddddddddddddddddddddddddddddddddd4444ff..
...ffe44444ddddddddddddddddddddddddddddddddddddddddddd44444ff...
....fff44444444444444444444444444444444444444444444444444eff....
.....fff444444444444444444444444444444444444444444444444fff.....
......fffffe44444444444444444444444444444444444444444fffff......
........ffffffffffffffffffffffffffffffffffffffffffffffff........
............fffffffffffffffffffffffffffffffffffffffff...........
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "Y%ww1ghU:FE/J2j_LI*s":
            case "amogusMouse1":return img`
......................
......................
......................
....ffcdfffff.........
...ffdc1bfbcf.........
....fdddbfb1f.........
....f111bcb1f.........
....f111bbc1ff........
....f111dfffff........
....ffdcff77ff........
...f77fc77777f........
...f7cffff7776f.......
...ff9999cf776ffff....
..fbd11996c776f77ff...
..f91d999ccf766f66f...
..f99999cccf776f66f...
..fcccccccf7776f666f..
...fcccccf777766f66f..
....fffc77777766f66f..
....f77777777766f66f..
....f77777777666f66c..
....f677777766666f6f..
....f666666666666fff..
.....f66666666666f....
.....f66666ff6666f....
......f6fffff6666f....
......f666f..f666f....
.......c666f.f666f....
.......f66ff.ffff.....
........ff............
......................
......................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "MouseAnimation1":
            case "?($|rg3vYW-izp!nNgL1":return [img`
................................
................................
................................
....f...........................
....f...........................
....f...........................
.....f........fff...............
.....f.......f991fff............
.....ff.....fc991df7f...........
......f....f7c9991c77f.fffff....
......ff...77cc999b77fcbdddf....
......ff..f77fccccf77f11111d....
......f6ff.f77fcccc77f11111bf...
.......ff.ff777777777f11dbd1f...
.......ff.ff777777777fcbbbbc....
.......f6fff7777777776ffffff....
........ff..f777777766fdddbf....
........f6f.f77777766ffddcf.....
....f.f.f6fff777666ffffffff.....
...ff....f6fc766fff677..........
..f7cfffffff777cf6667f..........
..f677777777667ff66cf...........
...f666666666fff6fff............
...f6f66666666cc6f..............
...f66ffffc666c.f...............
...f666f..f666f.................
...f666f..f666f.................
....ffff..f666f.................
..........ffcff.................
................................
................................
................................
`];
            case "MouseAnimation2":
            case "](^AALc?FbsF?PZ|vt":return [img`
......................
......................
......................
....ffcdfffff.........
...ffdc1bfbcf.........
....fdddbfb1f.........
....f111bcb1f.........
....f111bbc1ff........
....f111dfffff........
....ffdcff77ff........
...f77fc77777f........
...f7cffff7776f.......
...ff9999cf776ffff....
..fbd11996c776f77ff...
..f91d999ccf766f66f...
..f99999cccf776f66f...
..fcccccccf7776f666f..
...fcccccf777766f66f..
....fffc77777766f66f..
....f77777777766f66f..
....f77777777666f66c..
....f677777766666f6f..
....f666666666666fff..
.....f66666666666f....
.....f66666ff6666f....
......f6fffff6666f....
......f666f..f666f....
.......c666f.f666f....
.......f66ff.ffff.....
........ff............
......................
......................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
